from android2harmony.runtime_verify import parse_jscrash


SAMPLE = """Generated by HiviewDFX@OpenHarmony
Module name:com.generated.simplegallery
Version:1.0.0
Reason:ReferenceError
Error name:ReferenceError
Error message:$isRefreshing is not defined
Stacktrace:
Cannot get SourceMap info, dump raw stack:
    at anonymous (entry|entry|1.0.0|src/main/ets/pages/MainActivity.ts:203:1)
    at updateFunc (.../stateMgmt.js:8720:1)
    at initialRender (entry|entry|1.0.0|src/main/ets/pages/MainActivity.ts:201:14)
"""


def test_parse_jscrash_extracts_error_and_page():
    crash = parse_jscrash(SAMPLE)
    assert crash is not None
    assert crash.error == "ReferenceError: $isRefreshing is not defined"
    assert crash.ets_relpath == "pages/MainActivity.ets"


def test_parse_jscrash_handles_nested_fragment_path():
    log = (
        "Error name:TypeError\nError message:Cannot read property 'x' of undefined\n"
        "Stacktrace:\n    at foo (entry|entry|1.0.0|src/main/ets/pages/FragmentHome.ts:88:3)\n"
    )
    crash = parse_jscrash(log)
    assert crash.error.startswith("TypeError: Cannot read property")
    assert crash.ets_relpath == "pages/FragmentHome.ets"


def test_parse_jscrash_none_when_no_crash():
    assert parse_jscrash("just some normal log\nnothing here") is None
